/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const StoreOrders = [
         {
           id: 1,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
    phone: '08114426271',
           orderStage: "processed",
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 2,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 3,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 4,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,

             },
           ],
         },
         {
           id: 5,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 6,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 7,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 8,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 9,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 10,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 11,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 12,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "not paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
         {
           id: 13,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           status: "paid",
           deliveryType: "Doorstep delivery",
           paymentType: "paymentType",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phone: '08114426271',
           cart: [
             {
               id: 1,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
             {
               id: 2,
               title: "Samsung S7",
               img: "img/product-2.png",
               price: 16,
               company: "SAMSUNG",
               info:
                 "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
               inCart: false,
               count: 0,
               total: 0,
             },
           ],
         },
       ];


