/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const UsersData = [
         {
           id: 1,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "aaaaaaaaaoluseyi@gmail.com",
           role: "user",
         },
         {
           id: 2,
           firstName: "Oluseyi",
           lastName: "Alawiyeeee",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 3,
           firstName: "Oluddseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 4,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 5,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 6,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 7,
           firstName: "Olukayode",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 8,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 9,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 10,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 11,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 12,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
         {
           id: 13,
           firstName: "Oluseyi",
           lastName: "Alawiye",
           userLGA: "userLGA",
           userstate: "userstate",
           address: "address",
           phoneNumber: "08114426271",
           email: "oluseyi@gmail.com",
           role: "user",
         },
       ];


